
MazeTest: MazeTest.cpp Maze.o Maze.h List.hpp OrderedPair.h
	g++ MazeTest.cpp Maze.o -o MazeTest

Maze.o: Maze.cpp Maze.h
	g++ -c Maze.cpp -o Maze.o

ListTest: ListTest.cpp List.hpp
	g++ ListTest.cpp  -o ListTest
