CircularDoublyLinkedListTest: CircularDoublyLinkedListTest.cpp CircularDoublyLinkedList.o CircularDoublyLinkedList.h
	g++ CircularDoublyLinkedListTest.cpp CircularDoublyLinkedList.o -o CircularDoublyLinkedListTest

CircularDoublyLinkedList.o: CircularDoublyLinkedList.cpp CircularDoublyLinkedList.h
	g++ -c CircularDoublyLinkedList.cpp -o CircularDoublyLinkedList.o


