
DateType.o: DateType.cpp DateType.h RelationType.h
	g++ -c DateType.cpp -o DateType.o

DateTypeTest: DateTypeTest.cpp DateType.h RelationType.h DateType.o
	g++ DateTypeTest.cpp DateType.o -o DateTypeTest
